stages:
  - build

artefacts:
  stage: build
  script:
    - "./gradlew applyPatches"
    - "./gradlew shadowJar"
    - "./gradlew reobf"
    - "./gradlew paperclipJar"
  artifacts:
    name: "$CI_BUILD_REF_NAME"
    expire_in: '1 week'
    paths:
      - "Weeper-API/build/libs/*.jar"
