group=com.github.weepingmc.weeper
mcVersion=26.3-snapshot-10
version=26.3-R0.1-SNAPSHOT
# This is the current API version for use in (paper-)plugin.yml files
# During snapshot cycles this should be the anticipated version of the release target
apiVersion=26.3
channel=ALPHA

paperRef=0b1e362a9b9bad35892786cb6a204f4a25a8e920

org.gradle.configuration-cache=true
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.vfs.watch=false
