group=com.github.weepingmc.weeper
mcVersion=26.3-pre-1
version=26.3-R0.1-SNAPSHOT
# This is the current API version for use in (paper-)plugin.yml files
# During snapshot cycles this should be the anticipated version of the release target
apiVersion=26.3
channel=ALPHA

paperRef=83b7a830f864ba7d539500ad5cb024e12bbd3fdf

org.gradle.configuration-cache=true
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.vfs.watch=false
