group=com.github.weepingmc.weeper
mcVersion=26.3
version=26.3-R0.1-SNAPSHOT
# This is the current API version for use in (paper-)plugin.yml files
# During snapshot cycles this should be the anticipated version of the release target
apiVersion=26.3
channel=ALPHA

paperRef=ace932ed4e72bc7843cc4af1fa877da4ca8b2f1e

org.gradle.configuration-cache=true
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.vfs.watch=false
