on:
  push:
    branches:
      - master
      - main
      - develop
    tags:
      - '*.*.*'
jobs:
  build:
    strategy:
      matrix:
        java-version: [ '21' ]
        os: [ 'ubuntu-latest']
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
      - name: Setup Java ${{ matrix.java-version }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java-version }}
          architecture: x64
      - name: Set fake github mail
        run: git config --global user.email "dummy@example.com"
      - name: Set fake github user
        run: git config --global user.name "Master Dummy"
      - name: Apply Patches
        run: ./gradlew applyPatches
      - name: Generate moj Paperclip jar
        run: ./gradlew createMojmapPaperclipJar
      - uses: actions/upload-artifact@v4
        with:
          name: "paperclip"
          path: "build/libs/Weeper-paperclip-*-mojmap.jar"
      - name: Generate reobf Paperclip jar
        run: ./gradlew createReobfPaperclipJar
      - uses: actions/upload-artifact@v4
        with:
          name: "paperclip"
          path: "build/libs/Weeper-paperclip-*-reobf.jar"
